language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - py.test
  - coverage run --source=cobra -m pytest
after_success:
  - coveralls